name: test workflow
on: 
   push:
   workflow_dispatch:
jobs:
    first-job:
       runs-on: ubuntu-latest
       steps:
         - name: get time and date
           run: |
              run: echo "::set-output name=date::$(date +'%Y-%m-%d')"